### ISSUE TITLE
Lutris dont start with new vulkan-icd-loader-git (1.2.137.r3.g95a4ccd0f)

### ISSUE THREAD

**Issue by xavatar** [Frogging-Family/vulkan-icd-loader-git#1]
Hello,

Just for information, i can't start lutris with the last build : vulkan-icd-loader-git-1.2.137.r3.g95a4ccd0f
INFO     2020-04-11 22:39:42,717 [application.do_command_line:245]:Running Lutris 0.5.5
INFO     2020-04-11 22:39:42,718 [startup.check_driver:54]:Using NVIDIA drivers 440.82 for x86_64
INFO     2020-04-11 22:39:42,718 [startup.check_driver:60]:GPU: GeForce GTX 970
INFO     2020-04-11 22:39:42,718 [startup.check_driver:77]:GPU: 10DE:13C2 1462:3160 using nvidia drivers
Stuck at this step and nothing appear...

If i downgrade to vulkan-icd-loader-git-1.2.135.r7.gba07fa0be, no problem, lutris start normaly =>
INFO     2020-04-11 22:34:41,724 [application.do_command_line:245]:Running Lutris 0.5.5
INFO     2020-04-11 22:34:41,725 [startup.check_driver:54]:Using NVIDIA drivers 440.82 for x86_64
INFO     2020-04-11 22:34:41,725 [startup.check_driver:60]:GPU: GeForce GTX 970
INFO     2020-04-11 22:34:41,725 [startup.check_driver:77]:GPU: 10DE:13C2 1462:3160 using nvidia drivers
INFO     2020-04-11 22:34:41,798 [startup.check_vulkan:132]:Vulkan is supported
INFO     2020-04-11 22:34:41,799 [dxvk.get_dxvk_versions:22]:Updating DXVK versions
DEBUG    2020-04-11 22:34:41,994 [http.get:65]:GET https://lutris.net/api/runtime
INFO     2020-04-11 22:34:55,567 [application.do_shutdown:491]:Shutting down Lutris

Amicalement ;-)
Xavatar

**Comment by Tk-Glitch** [comment]
The problem was fixed upstream 13 hours ago: https://github.com/KhronosGroup/Vulkan-Loader/commits/master

**Comment by xavatar** [comment]
Yes right, with 1.2.137.r4.g3f7e3cbf3-1 it's OK !
