### ISSUE TITLE
can not be installed because mesa wants libvulkan.so=1-64, which the package doesn't provide

### ISSUE THREAD

**Issue by fsyy** [Frogging-Family/vulkan-icd-loader-git#2]
:: vulkan-icd-loader-git and vulkan-icd-loader are in conflict. Remove vulkan-icd-loader? [y/N] y
error: failed to prepare transaction (could not satisfy dependencies)
:: removing vulkan-icd-loader breaks dependency 'libvulkan.so=1-64' required by mesa
==> WARNING: Failed to install built package(s).
  -> exit cleanup done

lib32 package seems not to be affected

**Comment by fsyy** [comment]
still complaining:

resolving dependencies...
looking for conflicting packages...
error: failed to prepare transaction (could not satisfy dependencies)
:: installing vulkan-icd-loader-git (1.2.170.r0.gc5678a03d-1) breaks dependency 'libvulkan.so=1-64' required by mesa
==> WARNING: Failed to install built package(s).
  -> exit cleanup done

if i modify 

 provides=("vulkan-icd-loader=$pkgver-$pkgrel" "libvulkan.so=$pkgver-$pkgrel")

to 

 provides=("vulkan-icd-loader=$pkgver-$pkgrel" "libvulkan.so")

it's accepted.

**Comment by Tk-Glitch** [comment]
Is that even supposed to work with stable mesa anyway? :frog:
Oh well, I'll nuke the versioning to make the dependency check shut up. Thanks for feedback.
