### ISSUE TITLE
Cannot find library listed in 'provides': lib32-libvulkan.so

### ISSUE THREAD

**Issue by ryanmusante** [Frogging-Family/vulkan-icd-loader-git#5]
Is the build not finishing despite successfully compiling?
```
==> Checking for packaging issues...
==> Creating package "lib32-vulkan-icd-loader-git"...
  -> Generating .PKGINFO file...
==> WARNING: Cannot find library listed in 'provides': lib32-libvulkan.so
```

**Comment by Tk-Glitch** [comment]
It was a naming scheme quirk needed by other apps at some point. It seems we might be able to remove it now.
But no, there's nothing missing in the package, it's just that the lib is `libvulkan.so` for both 32 and 64-bit packages.
